# Generated by Django 3.2.10 on 2022-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
